version: 2
updates:
# Fetch and update latest `npm` packages
- package-ecosystem: npm
  directory: '/'
  schedule:
    interval: daily
    time: '00:00'
  open-pull-requests-limit: 10
  reviewers:
    - yasudanaoya
  assignees:
    - yasudanaoya
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
  ignore:
    - dependency-name: "node-sass"
      versions: ["5.x"]
    - dependency-name: "sass-loader"
      versions: ["11.x"]

# Fetch and update latest `github-actions` pkgs
- package-ecosystem: github-actions
  directory: '/'
  schedule:
    interval: daily
    time: '00:00'
  open-pull-requests-limit: 10
  reviewers:
    - yasudanaoya
  assignees:
    - yasudanaoya
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
