#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

for EXTENSION in `git diff --cached --name-only | sed 's/^.*\.\([^\.]*\)$/\1/'`; do
  TARGET=('js' "ts" "tsx")
  if [[ " ${TARGET[@]} " =~ " ${EXTENSION} " ]]; then
    # yarn test
    yarn lint --max-warnings=0
    break
  fi
done
